// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axnsveyfhsubafsrapnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4bnN2ZXlmaHN1YmFmc3JhcG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODM4MTMsImV4cCI6MjA3MzM1OTgxM30.JMBPOQHmFdqJ4W1iEsAJU3SWDbqXqwBY0BAhzWqEJ2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});